#!/bin/bash

source "${CFHVENV}/activate"
python "${CFHDIR}/main.py" $1
# * CFHVENV is a environment variable to the virtual-env that has bs4 and requests
# * CFHDIR is a path where codeforces-helper is cloned
# ! YOURS WILL BE DIFFERENT

cd $DIRFORCES